name: "dbt_exercise"
version: "1.0.0"

profile: "dbt_exercise"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_exercise:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
